### ISSUE TITLE
The time frame should also apply to "Details for all queries".

### ISSUE THREAD

**Issue by yhuelf** [dalibo/powa-web#6]

**Comment by rjuju** [comment]
Hello,

Sorry for late reply.  The time frame should apply to every data, including the "Details for all queryies" grid. Can you provide some more details on this issue?

**Comment by rjuju** [comment]
Hello again,
do you still encounter this problem?

**Comment by yhuelf** [comment]
oops sorry, my powa setup was on a server which has been replaced. But I will install it again and tell you, this week I hope.

**Comment by yhuelf** [comment]
On a fresh new install of powa (powa-archivist from the Postgresql's maintained debian jessie repository, and powa-web master), I can see that the time frame does apply to the "Details for all queries" window.

I noticed inconsistencies though : some queries don't appear, even after 10 min (powa.frequency defaults to 5 min if I'm not wrong). Anyway, this is the subject for a different issue, and I guess you can close this very one.

**Comment by rjuju** [comment]
Ok, thanks for the feedblack. I'm closing this issue then.

For your other problem, feel free to open a new issue if needed. But maybe what you encounter is the "normal" behavior of powa, ie. showing queries that have been executing on at least two different snapshots.  If the query has been executed a thousand time all in the same snapshot interval, and then never again, it won't be displayed on the UI.  That's a known limitation and we'll do our best to fix it, but since these queries are usually not the one you need to optimize it hasn't been a high-priority.

**Comment by yhuelf** [comment]
> maybe what you encounter is the "normal" behavior of powa, ie. showing queries that have been executing on at least two different snapshots

Indeed you're most probably right, even though I didn't check carefully, it makes sense. I don't think it's problematic, but maybe it should be mentioned in the documentation so that one is not surprised when testing powa. Anyway, thanks for your answer!

**Comment by rjuju** [comment]
Good idea! I started a FAQ section on the documentation with this item: http://powa.readthedocs.io/en/latest/FAQ.html
